[project]
name = "srgan-from-scratch-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "albumentations>=2.0.8",
    "ipykernel>=6.31.0",
    "pillow>=11.3.0",
    "torch>=2.8.0",
]
